//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapBoard.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapBoard.Common.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string DisplayFieldName {
            get {
                return ResourceManager.GetString("DisplayFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;labelExpressionInfo&quot;: {
        ///    &quot;expression&quot;: &quot;$feature.Info&quot;
        ///  },
        ///  &quot;maxScale&quot;: 0,
        ///  &quot;minScale&quot;: 0,
        ///  &quot;symbol&quot;: {
        ///    &quot;angle&quot;: 0,
        ///    &quot;backgroundColor&quot;: [
        ///      0,
        ///      0,
        ///      0,
        ///      0
        ///    ],
        ///    &quot;borderLineColor&quot;: [
        ///      0,
        ///      0,
        ///      0,
        ///      0
        ///    ],
        ///    &quot;borderLineSize&quot;: 0,
        ///    &quot;color&quot;: [
        ///      0,
        ///      0,
        ///      0,
        ///      255
        ///    ],
        ///    &quot;font&quot;: {
        ///      &quot;decoration&quot;: &quot;none&quot;,
        ///      &quot;size&quot;: 15,
        ///      &quot;style&quot;: &quot;normal&quot;,
        ///      &quot;weight&quot;: &quot;normal&quot;
        ///    },
        ///    &quot;haloCol [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string LabelJson {
            get {
                return ResourceManager.GetString("LabelJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] MultipointCpg {
            get {
                object obj = ResourceManager.GetObject("MultipointCpg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] MultipointDbf {
            get {
                object obj = ResourceManager.GetObject("MultipointDbf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] MultipointPrj {
            get {
                object obj = ResourceManager.GetObject("MultipointPrj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] MultipointShp {
            get {
                object obj = ResourceManager.GetObject("MultipointShp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] MultipointShx {
            get {
                object obj = ResourceManager.GetObject("MultipointShx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PointCpg {
            get {
                object obj = ResourceManager.GetObject("PointCpg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PointDbf {
            get {
                object obj = ResourceManager.GetObject("PointDbf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PointPrj {
            get {
                object obj = ResourceManager.GetObject("PointPrj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PointShp {
            get {
                object obj = ResourceManager.GetObject("PointShp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PointShx {
            get {
                object obj = ResourceManager.GetObject("PointShx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PolygonCpg {
            get {
                object obj = ResourceManager.GetObject("PolygonCpg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PolygonDbf {
            get {
                object obj = ResourceManager.GetObject("PolygonDbf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PolygonPrj {
            get {
                object obj = ResourceManager.GetObject("PolygonPrj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PolygonShp {
            get {
                object obj = ResourceManager.GetObject("PolygonShp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PolygonShx {
            get {
                object obj = ResourceManager.GetObject("PolygonShx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PolylineCpg {
            get {
                object obj = ResourceManager.GetObject("PolylineCpg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PolylineDbf {
            get {
                object obj = ResourceManager.GetObject("PolylineDbf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PolylinePrj {
            get {
                object obj = ResourceManager.GetObject("PolylinePrj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PolylineShp {
            get {
                object obj = ResourceManager.GetObject("PolylineShp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] PolylineShx {
            get {
                object obj = ResourceManager.GetObject("PolylineShx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string TimeExtentFieldName {
            get {
                return ResourceManager.GetString("TimeExtentFieldName", resourceCulture);
            }
        }
    }
}
